name: Sync Auth OAS to ReadMe
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/github-readme-sync@v2.0.0
        with:
          readme-oas-key: ${{ secrets.README_OAS_KEY }}
           
          # OPTIONAL CONFIG, use if necessary
          oas-file-path: './Authorization_API_stoplight_studio.yaml'
          api-version: 'v1.0'